export const REQUEST_FETCH_PRODUCTS = 'REQUEST_FETCH_PRODUCTS';
export const RECEIVE_FETCH_PRODUCTS = 'RECEIVE_FETCH_PRODUCTS';
export const REQUEST_CREATE_PRODUCT = 'REQUEST_CREATE_PRODUCT';
export const REQUEST_EDIT_PRODUCT = 'REQUEST_EDIT_PRODUCT';
export const RECEIVE_EDIT_PRODUCT = 'RECEIVE_EDIT_PRODUCT';
export const REQUEST_UPDATE_PRODUCT = 'REQUEST_UPDATE_PRODUCT';
export const REQUEST_DELETE_PRODUCT = 'REQUEST_DELETE_PRODUCT';